<?php $_asyncCollection = $this->getAsyncCollection() ?>

<br/>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo Mage::helper('adminhtml')->__('Asynchronous Cache Management') ?></h3></td>
            <?php if (count($_asyncCollection) > 0): ?>
            	<td class="form-buttons"><button onclick="setLocation('<?php echo $this->getUrl('*/async/process')?>')" type="button" class="scalable delete"><span><?php echo Mage::helper('adminhtml')->__('Process asynchronous queue') ?></span></button></td>
            <?php endif; ?>
         </tr>
    </table>
</div>

<?php if (count($_asyncCollection) > 0): ?>

	<h4><?php echo Mage::helper('adminhtml')->__('Summary') ?>:</h4>
	<div class="grid">
		<table class="data" cellspacing="0">
			<thead>
	        	<tr class="headings">
	                <th class=" no-link"><span class="nobr">Mode</span></th>
	                <th class=" no-link last"><span class="nobr">Tags</span></th>
				</tr>
	        </thead>
			<tbody>
			<?php $i = 0;?>
			<?php foreach ($_asyncCollection->extractJobs() as $job): ?>
				<tr <?php echo ($i++ % 2) ? '' : 'class="even"'; ?>>
					<td><?php echo $job['mode']; ?></td>
					<td class="a-left last"><?php echo implode('<br />', $job['tags']); ?></td>
				</tr>	
			<?php endforeach; ?>
			</tbody>
		</table>
	</div>
	
	<h4><?php echo Mage::helper('adminhtml')->__('Single records') ?>:</h4>
	<div class="grid">
		<table class="data" cellspacing="0">
			<thead>
	        	<tr class="headings">
	                <th class="no-link"><span class="nobr"><?php echo Mage::helper('adminhtml')->__('Time') ?></span></th>
	                <th class="no-link"><span class="nobr"><?php echo Mage::helper('adminhtml')->__('Mode') ?></span></th>
	                <th class="no-link"><span class="nobr"><?php echo Mage::helper('adminhtml')->__('Tags') ?></span></th>
	                <th class="no-link last"><span class="nobr"><?php echo Mage::helper('adminhtml')->__('Action') ?></span></th>
				</tr>
	        </thead>
			<tbody>
			<?php $i = 0;?>
			<?php foreach ($_asyncCollection as $async): ?>
				<tr <?php echo ($i++ % 2) ? '' : 'class="even"'; ?>>
					<td><?php echo date('H:i:s', Mage::getModel('core/date')->timestamp($async->getTstamp())); ?></td>
					<td><?php echo $async->getMode(); ?></td>
					<td class="a-left"><?php echo $async->getTags(); ?></td>
					<td class="a-left last"><a href="<?php echo $this->getUrl('*/async/delete', array('id' => $async->getId())); ?>"><?php echo Mage::helper('adminhtml')->__('Delete') ?></a></td>
					<!--<td><?php echo $async->getTrace(); ?></td>-->
				</tr>	
			<?php endforeach; ?>
			</tbody>
		</table>
	</div>

<?php else: ?>
	<?php echo Mage::helper('adminhtml')->__('No pending queue entries available.') ?>
<?php endif; ?>